package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class input implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Input_CAM_ASSET_USAGE_CODE")
	private int Input_CAM_ASSET_USAGE_CODE;
	@org.kie.api.definition.type.Label("Input_ASSET_CLASS")
	private java.lang.String Input_ASSET_CLASS;
	@org.kie.api.definition.type.Label("STP_COLOR")
	private java.lang.String STP_COLOR;
	@org.kie.api.definition.type.Label("LTV")
	private int LTV;
	@org.kie.api.definition.type.Label("Input_Tenure")
	private java.lang.Float Input_Tenure;

	@org.kie.api.definition.type.Label("Input_FINANCE_AMOUNT")
	private float Input_FINANCE_AMOUNT;

	@org.kie.api.definition.type.Label("Input_ASSET_MAKE")
	private java.lang.String Input_ASSET_MAKE;

	@org.kie.api.definition.type.Label("Input_RESIDENTIAL_TYPE")
	private java.lang.String Input_RESIDENTIAL_TYPE;

	@org.kie.api.definition.type.Label("Input_REGION_CODE")
	private java.lang.String Input_REGION_CODE;

	@org.kie.api.definition.type.Label("Input_ASSET_LEVEL4")
	private java.lang.String Input_ASSET_LEVEL4;

	@org.kie.api.definition.type.Label(value = "Input_ASSET_TYPE_ID")
	private int Input_ASSET_TYPE_ID;

	public input() {
	}

	public int getInput_CAM_ASSET_USAGE_CODE() {
		return this.Input_CAM_ASSET_USAGE_CODE;
	}

	public void setInput_CAM_ASSET_USAGE_CODE(int Input_CAM_ASSET_USAGE_CODE) {
		this.Input_CAM_ASSET_USAGE_CODE = Input_CAM_ASSET_USAGE_CODE;
	}

	public java.lang.String getInput_ASSET_CLASS() {
		return this.Input_ASSET_CLASS;
	}

	public void setInput_ASSET_CLASS(java.lang.String Input_ASSET_CLASS) {
		this.Input_ASSET_CLASS = Input_ASSET_CLASS;
	}

	public java.lang.String getSTP_COLOR() {
		return this.STP_COLOR;
	}

	public void setSTP_COLOR(java.lang.String STP_COLOR) {
		this.STP_COLOR = STP_COLOR;
	}

	public int getLTV() {
		return this.LTV;
	}

	public void setLTV(int LTV) {
		this.LTV = LTV;
	}

	public void setInput_Tenure(java.lang.Float Input_Tenure) {
		this.Input_Tenure = Input_Tenure;
	}

	public void setInput_FINANCE_AMOUNT(float Input_FINANCE_AMOUNT) {
		this.Input_FINANCE_AMOUNT = Input_FINANCE_AMOUNT;
	}

	public java.lang.String getInput_ASSET_MAKE() {
		return this.Input_ASSET_MAKE;
	}

	public void setInput_ASSET_MAKE(java.lang.String Input_ASSET_MAKE) {
		this.Input_ASSET_MAKE = Input_ASSET_MAKE;
	}

	public java.lang.String getInput_RESIDENTIAL_TYPE() {
		return this.Input_RESIDENTIAL_TYPE;
	}

	public void setInput_RESIDENTIAL_TYPE(
			java.lang.String Input_RESIDENTIAL_TYPE) {
		this.Input_RESIDENTIAL_TYPE = Input_RESIDENTIAL_TYPE;
	}

	public input(int Input_CAM_ASSET_USAGE_CODE,
			java.lang.String Input_ASSET_CLASS, java.lang.String STP_COLOR,
			int LTV, java.lang.String Input_REGION_NAME,
			java.lang.String Input_ASSET_TYPE, java.lang.Float Input_Tenure,
			float Input_FINANCE_AMOUNT, java.lang.String Input_ASSET_MAKE,
			java.lang.String Input_RESIDENTIAL_TYPE) {
		this.Input_CAM_ASSET_USAGE_CODE = Input_CAM_ASSET_USAGE_CODE;
		this.Input_ASSET_CLASS = Input_ASSET_CLASS;
		this.STP_COLOR = STP_COLOR;
		this.LTV = LTV;
		this.Input_Tenure = Input_Tenure;
		this.Input_FINANCE_AMOUNT = Input_FINANCE_AMOUNT;
		this.Input_ASSET_MAKE = Input_ASSET_MAKE;
		this.Input_RESIDENTIAL_TYPE = Input_RESIDENTIAL_TYPE;
	}

	public java.lang.String getInput_REGION_CODE() {
		return this.Input_REGION_CODE;
	}

	public void setInput_REGION_CODE(java.lang.String Input_REGION_CODE) {
		this.Input_REGION_CODE = Input_REGION_CODE;
	}

	public java.lang.String getInput_ASSET_LEVEL4() {
		return this.Input_ASSET_LEVEL4;
	}

	public void setInput_ASSET_LEVEL4(java.lang.String Input_ASSET_LEVEL4) {
		this.Input_ASSET_LEVEL4 = Input_ASSET_LEVEL4;
	}

	public input(int Input_CAM_ASSET_USAGE_CODE,
			java.lang.String Input_ASSET_CLASS, java.lang.String STP_COLOR,
			int LTV, java.lang.String Input_ASSET_TYPE,
			java.lang.Float Input_Tenure, float Input_FINANCE_AMOUNT,
			java.lang.String Input_ASSET_MAKE,
			java.lang.String Input_RESIDENTIAL_TYPE,
			java.lang.String Input_ASSET_CATEGORY,
			java.lang.String Input_REGION_CODE,
			java.lang.String Input_ASSET_LEVEL4) {
		this.Input_CAM_ASSET_USAGE_CODE = Input_CAM_ASSET_USAGE_CODE;
		this.Input_ASSET_CLASS = Input_ASSET_CLASS;
		this.STP_COLOR = STP_COLOR;
		this.LTV = LTV;
		this.Input_Tenure = Input_Tenure;
		this.Input_FINANCE_AMOUNT = Input_FINANCE_AMOUNT;
		this.Input_ASSET_MAKE = Input_ASSET_MAKE;
		this.Input_RESIDENTIAL_TYPE = Input_RESIDENTIAL_TYPE;
		this.Input_REGION_CODE = Input_REGION_CODE;
		this.Input_ASSET_LEVEL4 = Input_ASSET_LEVEL4;
	}

	public int getInput_ASSET_TYPE_ID() {
		return this.Input_ASSET_TYPE_ID;
	}

	public void setInput_ASSET_TYPE_ID(int Input_ASSET_TYPE_ID) {
		this.Input_ASSET_TYPE_ID = Input_ASSET_TYPE_ID;
	}

	public input(int Input_CAM_ASSET_USAGE_CODE,
			java.lang.String Input_ASSET_CLASS, java.lang.String STP_COLOR,
			int LTV, java.lang.Float Input_Tenure, float Input_FINANCE_AMOUNT,
			java.lang.String Input_ASSET_MAKE,
			java.lang.String Input_RESIDENTIAL_TYPE,
			java.lang.String Input_REGION_CODE,
			java.lang.String Input_ASSET_LEVEL4, int Input_ASSET_TYPE_ID) {
		this.Input_CAM_ASSET_USAGE_CODE = Input_CAM_ASSET_USAGE_CODE;
		this.Input_ASSET_CLASS = Input_ASSET_CLASS;
		this.STP_COLOR = STP_COLOR;
		this.LTV = LTV;
		this.Input_Tenure = Input_Tenure;
		this.Input_FINANCE_AMOUNT = Input_FINANCE_AMOUNT;
		this.Input_ASSET_MAKE = Input_ASSET_MAKE;
		this.Input_RESIDENTIAL_TYPE = Input_RESIDENTIAL_TYPE;
		this.Input_REGION_CODE = Input_REGION_CODE;
		this.Input_ASSET_LEVEL4 = Input_ASSET_LEVEL4;
		this.Input_ASSET_TYPE_ID = Input_ASSET_TYPE_ID;
	}

}